//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrift_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Billing
    {
        [Display(Name = "ID")]
        public int B_id { get; set; }
        [Display(Name = "Billing Name")]
        public string B_Name { get; set; }
        [Display(Name = "Address")]
        public string B_Address { get; set; }
        [Display(Name = "Total")]
        public Nullable<int> B_Total { get; set; }
        [Display(Name = "E-Mail")]
        public string B_email { get; set; }
        [Display(Name = "City")]
        public string B_city { get; set; }
        [Display(Name = "Postal")]
        public Nullable<int> B_Postal { get; set; }
        [Display(Name = "User ID")]
        public Nullable<int> B_User_ID { get; set; }
    }
}
