//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrift_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class product
    {
        [Display(Name = "ID")]
        public int P_ID { get; set; }
        [Display(Name = "NAme")]
        public string P_Name { get; set; }
        [Display(Name = "Discrpition")]
        public string P_Discription { get; set; }
        [Display(Name = "Discounted Price")]
        public Nullable<int> P_Discount { get; set; }
        [Display(Name = "Old Price" )]
        public Nullable<int> P_Price { get; set; }
        [Display(Name = "Stock")]
        public Nullable<int> P_Stock { get; set; }
                [Display(Name = "Picture")]
        public string P_Pic { get; set; }
        [Display(Name = "Category")]
        public string P_Type { get; set; }
    }
}
