//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrift_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Review
    {
        public int R_id { get; set; }
        public string R_Name { get; set; }
        public string R_Title { get; set; }
        public string R_discriptiopn { get; set; }
        public Nullable<int> R_ProID { get; set; }
    }
}
