//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thrift_Fashion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [Display(Name = "ID")]
        public int U_id { get; set; }
        [Display(Name = "Name")]
        public string U_Name { get; set; }
        [Display(Name = "E-Mail")]
        public string U_Email { get; set; }
        [Display(Name = "Contact")]
        public string U_Contact { get; set; }
        [Display(Name = "Password")]
        public string U_Password { get; set; }
        [Display(Name = "Address")]
        public string U_Address { get; set; }
        [Display(Name = "Pic")]
        public string U_Pic { get; set; }
    }
}
